version: "1"
name: snaily-cad

services:
  - name: api
    type: backend
    # container_name: "snaily-cad-api"
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   target: api
    ports:
      - "${PORT_API}:${PORT_API}"
    # depends_on:
    #   - postgres
    # restart: always
    volumes:
      - ./apps/api/public:/snailycad/apps/api/public
    environment:
      NODE_ENV: production

  - name: client
    type: custom
    # container_name: "snaily-cad-client"
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   target: client
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"
    # depends_on:
    #   - postgres
    # restart: always
    environment:
      NODE_ENV: production
# networks:
#   - name: cad_web
#     external: true
